### ISSUE TITLE
Make vs CMake

### ISSUE THREAD

**Issue by pguthrey** [LLNL/RAJA-project-template#6]
What if my code uses Make as opposed to cmake?  How might I include RAJA and or CHAI?

**Comment by rhornung67** [comment]
We'll add a recipe for make to the directions.  It should be available sometime this week. Stay tuned.

**Comment by davidbeckingsale** [comment]
Added in #7

**Comment by rhornung67** [comment]
@pguthrey please let us know if this is what you were looking for.

**Comment by pguthrey** [comment]
Great! This is what I was hoping for.  One issue though, here is the relevant part of my Makefile 

`
include $(DOGPACK)/lib/Makefile.defs
include $(DOGPACK)/apps/2d/advection/lib/Makefile.defs
 
RAJADIR = $(DOGPACK)/submodules/RAJA

CXXFLAGS=-I$(INC_DIR) -std=c++11 -fopenmp -DENABLE_MPI -DENABLE_OPENMP -fopenmp -DENABLE_RAJA

INC_DIR =$(RAJADIR)/include
LIB_DIR =$(RAJADIR)/include/lib
LIBS=-lRAJA

CXX = mpic++
LINK = time $(CXX) $(CXXFLAGS) -L $(LIB_DIR) $(LIBS)  
`

This tells me that RAJA.hpp cannot find RAJA/config.hpp

`
/p/lustre1/guthrey1/dograja/submodules/RAJA/include/RAJA/RAJA.hpp:29:10: fatal error: RAJA/config.hpp: No such file or directory
 #include "RAJA/config.hpp"
`
However there is a config.hpp.in ?

**Comment by davidbeckingsale** [comment]
Hey @pguthrey - the `config.hpp` is generated when you build RAJA. This is why you need to use the `include` and `lib` directories from an installed copy of RAJA.

If you are trying to build RAJA as part of your project, I would recommend using make to call cmake for the RAJA build/install and then use the approach you currently have to include and link against those installed files.

Let us know if you have any other questions.
